/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DropdownComponent {
        "placeholder": string;
    }
    interface TableComponent {
        "dataSet": any[];
    }
}
export interface DropdownComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDropdownComponentElement;
}
declare global {
    interface HTMLDropdownComponentElement extends Components.DropdownComponent, HTMLStencilElement {
    }
    var HTMLDropdownComponentElement: {
        prototype: HTMLDropdownComponentElement;
        new (): HTMLDropdownComponentElement;
    };
    interface HTMLTableComponentElement extends Components.TableComponent, HTMLStencilElement {
    }
    var HTMLTableComponentElement: {
        prototype: HTMLTableComponentElement;
        new (): HTMLTableComponentElement;
    };
    interface HTMLElementTagNameMap {
        "dropdown-component": HTMLDropdownComponentElement;
        "table-component": HTMLTableComponentElement;
    }
}
declare namespace LocalJSX {
    interface DropdownComponent {
        "onSelected"?: (event: DropdownComponentCustomEvent<string>) => void;
        "placeholder"?: string;
    }
    interface TableComponent {
        "dataSet"?: any[];
    }
    interface IntrinsicElements {
        "dropdown-component": DropdownComponent;
        "table-component": TableComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dropdown-component": LocalJSX.DropdownComponent & JSXBase.HTMLAttributes<HTMLDropdownComponentElement>;
            "table-component": LocalJSX.TableComponent & JSXBase.HTMLAttributes<HTMLTableComponentElement>;
        }
    }
}
